export interface InventorySearch {
    IDs? :Array<number>;
    CreatedDateFrom:Date;
    CreatedDateTo:Date;
    UpdatedDateFrom :Date;
    UpdatedDateTo :Date;
    CreatedBy?:string;
    UpdatedBy :string;
    Comment :string;
    Customername :string;
    DeviceType :string;
    OrderNumber :number;
    ReorderingPoint :number;
    BR :number;
    ItemCode :number;
    Meter :number;
    Number :number;
    SerielNumber:string;
    RecipientName :string;
    ActionType:string;
    DateType:string;
    Status:string;
     ExpriyDateTo :Date;
     ExpriyDateFrom :Date;
     ReceivedDateTo :Date;
     ReceivedDateFrom :Date;
     TypeStatusId? :number;
     TypeStatusIDs? :Array<number>;
     TeamId? :number;
     TeamIDs? :Array<number>;
     ReceviedStatusId? :number;
     ReceviedStatusIDs? :Array<number>;
     OutgoingStatusId? :number;
     OutgoingStatusIDs? :Array<number>;
     CategoryId? :number;
     CategoryIDs? :Array<number>;
     CompanyId? :number;
     CompanyIDs? :Array<number>;
     ReceviedTypeId? :number;
     ReceviedTypeIDs? :Array<number>;
     AcceptanceIDs? :Array<number>;
     AcceptanceId? :number;
     LocationId? :number;
     LocationIDs? :Array<number>;
}
